package de.uniks.pmws2324.ludo;

import de.uniks.pmws2324.ludo.service.GameService;
import javafx.scene.canvas.Canvas;
import javafx.scene.input.MouseButton;
import javafx.stage.Stage;
import org.junit.jupiter.api.Test;
import org.testfx.framework.junit5.ApplicationTest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.testfx.api.FxAssert.verifyThat;
import static org.testfx.util.NodeQueryUtils.hasText;

class FullGameTest extends ApplicationTest {
    private Stage stage;
    private App app;
    Canvas canvas;

    @Override
    public void start(Stage stage) {
        this.stage = stage;
        this.app = new App(true);
        app.start(this.stage);
    }

    @Test
    public void test() {
        GameService gameService = app.getGameService();
        assertEquals("Ludo - Setup", stage.getTitle());

        clickOn("#firstPlayerField").write("Clemens");
        clickOn("#secondPlayerField").write("Natascha");

        clickOn("#startButton");

        assertEquals("Ludo", stage.getTitle());

        this.canvas = lookup("#boardCanvas").query();

        double xCenter = canvas.getWidth() / 2;
        double yCenter = canvas.getHeight() / 2;

        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(847.0 - xCenter, 359.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(639.0 - xCenter, 349.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(636.0 - xCenter, 359.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(635.0 - xCenter, 557.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(637.0 - xCenter, 559.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(536.0 - xCenter, 415.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(528.0 - xCenter, 413.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(485.0 - xCenter, 363.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(831.0 - xCenter, 375.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(725.0 - xCenter, 362.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(487.0 - xCenter, 371.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(341.0 - xCenter, 355.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(634.0 - xCenter, 76.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(629.0 - xCenter, 162.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(331.0 - xCenter, 370.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(397.0 - xCenter, 263.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(633.0 - xCenter, 160.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(687.0 - xCenter, 259.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(391.0 - xCenter, 266.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(535.0 - xCenter, 260.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(686.0 - xCenter, 243.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(682.0 - xCenter, 259.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(832.0 - xCenter, 257.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(540.0 - xCenter, 253.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(530.0 - xCenter, 106.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(842.0 - xCenter, 269.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(788.0 - xCenter, 356.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(542.0 - xCenter, 111.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(542.0 - xCenter, 47.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(787.0 - xCenter, 353.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(642.0 - xCenter, 358.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(533.0 - xCenter, 65.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(632.0 - xCenter, 78.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(637.0 - xCenter, 365.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(633.0 - xCenter, 458.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(636.0 - xCenter, 71.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(688.0 - xCenter, 251.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(633.0 - xCenter, 473.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(534.0 - xCenter, 511.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(690.0 - xCenter, 262.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(834.0 - xCenter, 310.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(536.0 - xCenter, 505.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(537.0 - xCenter, 412.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(844.0 - xCenter, 310.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(741.0 - xCenter, 304.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(536.0 - xCenter, 408.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(442.0 - xCenter, 351.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(745.0 - xCenter, 318.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(732.0 - xCenter, 307.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(830.0 - xCenter, 351.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(806.0 - xCenter, 356.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(794.0 - xCenter, 357.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(426.0 - xCenter, 363.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(381.0 - xCenter, 261.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(735.0 - xCenter, 307.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(691.0 - xCenter, 312.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(381.0 - xCenter, 264.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(435.0 - xCenter, 267.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(736.0 - xCenter, 369.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(637.0 - xCenter, 564.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(643.0 - xCenter, 568.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(532.0 - xCenter, 562.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(639.0 - xCenter, 63.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(734.0 - xCenter, 258.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(438.0 - xCenter, 258.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(533.0 - xCenter, 155.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(537.0 - xCenter, 554.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(437.0 - xCenter, 372.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(443.0 - xCenter, 363.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(428.0 - xCenter, 254.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(445.0 - xCenter, 253.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(539.0 - xCenter, 58.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(537.0 - xCenter, 61.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(637.0 - xCenter, 122.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(735.0 - xCenter, 253.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(784.0 - xCenter, 258.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(631.0 - xCenter, 115.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(637.0 - xCenter, 261.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(530.0 - xCenter, 156.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(530.0 - xCenter, 114.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(779.0 - xCenter, 357.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(634.0 - xCenter, 361.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(532.0 - xCenter, 105.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(535.0 - xCenter, 60.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(635.0 - xCenter, 361.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(636.0 - xCenter, 520.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(527.0 - xCenter, 67.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(576.0 - xCenter, 116.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(639.0 - xCenter, 254.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(837.0 - xCenter, 304.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(789.0 - xCenter, 254.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(838.0 - xCenter, 259.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(636.0 - xCenter, 512.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(530.0 - xCenter, 467.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(637.0 - xCenter, 64.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(744.0 - xCenter, 258.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(840.0 - xCenter, 260.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(787.0 - xCenter, 353.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(535.0 - xCenter, 465.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(387.0 - xCenter, 361.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(792.0 - xCenter, 362.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(638.0 - xCenter, 456.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(382.0 - xCenter, 361.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(429.0 - xCenter, 266.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(745.0 - xCenter, 263.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(734.0 - xCenter, 359.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(631.0 - xCenter, 460.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(535.0 - xCenter, 560.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(835.0 - xCenter, 313.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(739.0 - xCenter, 312.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(543.0 - xCenter, 557.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(536.0 - xCenter, 367.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(437.0 - xCenter, 254.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(538.0 - xCenter, 63.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(537.0 - xCenter, 68.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(637.0 - xCenter, 116.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(530.0 - xCenter, 367.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(336.0 - xCenter, 364.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(637.0 - xCenter, 115.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(727.0 - xCenter, 262.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(337.0 - xCenter, 363.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(336.0 - xCenter, 313.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(698.0 - xCenter, 310.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(638.0 - xCenter, 309.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(326.0 - xCenter, 303.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(536.0 - xCenter, 266.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(743.0 - xCenter, 254.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(685.0 - xCenter, 302.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(825.0 - xCenter, 361.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(631.0 - xCenter, 456.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(637.0 - xCenter, 458.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(529.0 - xCenter, 463.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(541.0 - xCenter, 460.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(536.0 - xCenter, 411.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(542.0 - xCenter, 248.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(540.0 - xCenter, 164.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(539.0 - xCenter, 415.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(484.0 - xCenter, 354.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(533.0 - xCenter, 159.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(583.0 - xCenter, 211.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(739.0 - xCenter, 365.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(631.0 - xCenter, 461.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(482.0 - xCenter, 366.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(392.0 - xCenter, 352.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(589.0 - xCenter, 215.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(585.0 - xCenter, 262.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(383.0 - xCenter, 360.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(384.0 - xCenter, 263.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(641.0 - xCenter, 61.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(636.0 - xCenter, 255.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(391.0 - xCenter, 263.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(530.0 - xCenter, 162.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(587.0 - xCenter, 114.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(585.0 - xCenter, 147.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(529.0 - xCenter, 164.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(632.0 - xCenter, 166.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(629.0 - xCenter, 163.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(737.0 - xCenter, 260.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(639.0 - xCenter, 267.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(795.0 - xCenter, 265.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(746.0 - xCenter, 262.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(835.0 - xCenter, 266.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(642.0 - xCenter, 454.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(640.0 - xCenter, 506.0 - yCenter).clickOn(MouseButton.PRIMARY);
        clickOn("#rollButton");
        verifyThat("#lastRoll", hasText(gameService.getGame().getRoll() + ""));
        moveTo(canvas);
        moveBy(829.0 - xCenter, 267.0 - yCenter).clickOn(MouseButton.PRIMARY);
        moveTo(canvas);
        moveBy(792.0 - xCenter, 300.0 - yCenter).clickOn(MouseButton.PRIMARY);

        assertEquals("Ludo - Game Over", stage.getTitle());

        verifyThat("#winnerLabel", hasText("Natascha won the game!"));
        verifyThat("#loserLabel", hasText("Clemens lost."));
    }
}